// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: detail.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const compareWorkDetailSnapshots = `-- name: CompareWorkDetailSnapshots :many
WITH
from_snapshots AS (
    SELECT
        s.work_href,
        s.category,
        s.title,
        s.release_date,
        s.metascore,
        s.user_score,
        s.rating,
        s.duration,
        s.tagline,
        s.details_json
    FROM work_detail_snapshots s
    WHERE s.crawl_run_id = ?2
      AND (?3 = '' OR s.category = ?3)
      AND (?4 = '' OR RTRIM(s.work_href, '/') = RTRIM(?4, '/'))
),
to_snapshots AS (
    SELECT
        s.work_href,
        s.category,
        s.title,
        s.release_date,
        s.metascore,
        s.user_score,
        s.rating,
        s.duration,
        s.tagline,
        s.details_json
    FROM work_detail_snapshots s
    WHERE s.crawl_run_id = ?5
      AND (?3 = '' OR s.category = ?3)
      AND (?4 = '' OR RTRIM(s.work_href, '/') = RTRIM(?4, '/'))
),
compare_rows AS (
    SELECT
        COALESCE(f.work_href, t.work_href) AS work_href,
        COALESCE(f.category, t.category) AS category,
        CASE WHEN f.work_href IS NULL THEN NULL ELSE f.title END AS from_title,
        t.title AS to_title,
        f.release_date AS from_release_date,
        t.release_date AS to_release_date,
        f.metascore AS from_metascore,
        t.metascore AS to_metascore,
        f.user_score AS from_user_score,
        t.user_score AS to_user_score,
        f.rating AS from_rating,
        t.rating AS to_rating,
        f.duration AS from_duration,
        t.duration AS to_duration,
        f.tagline AS from_tagline,
        t.tagline AS to_tagline,
        CASE WHEN f.work_href IS NULL THEN NULL ELSE f.details_json END AS from_details_json,
        t.details_json AS to_details_json,
        CASE
            WHEN f.work_href IS NOT NULL
             AND t.work_href IS NOT NULL
             AND IFNULL(f.details_json, '{}') <> IFNULL(t.details_json, '{}') THEN 1
            ELSE 0
        END AS details_json_changed,
        CASE
            WHEN f.work_href IS NULL THEN 'added'
            WHEN t.work_href IS NULL THEN 'removed'
            WHEN IFNULL(f.title, '') <> IFNULL(t.title, '')
              OR IFNULL(f.release_date, '') <> IFNULL(t.release_date, '')
              OR IFNULL(f.metascore, '') <> IFNULL(t.metascore, '')
              OR IFNULL(f.user_score, '') <> IFNULL(t.user_score, '')
              OR IFNULL(f.rating, '') <> IFNULL(t.rating, '')
              OR IFNULL(f.duration, '') <> IFNULL(t.duration, '')
              OR IFNULL(f.tagline, '') <> IFNULL(t.tagline, '')
              OR IFNULL(f.details_json, '{}') <> IFNULL(t.details_json, '{}') THEN 'changed'
            ELSE 'unchanged'
        END AS change_type
    FROM from_snapshots f
    LEFT JOIN to_snapshots t
      ON f.work_href = t.work_href

    UNION ALL

    SELECT
        COALESCE(f.work_href, t.work_href) AS work_href,
        COALESCE(f.category, t.category) AS category,
        CASE WHEN f.work_href IS NULL THEN NULL ELSE f.title END AS from_title,
        t.title AS to_title,
        f.release_date AS from_release_date,
        t.release_date AS to_release_date,
        f.metascore AS from_metascore,
        t.metascore AS to_metascore,
        f.user_score AS from_user_score,
        t.user_score AS to_user_score,
        f.rating AS from_rating,
        t.rating AS to_rating,
        f.duration AS from_duration,
        t.duration AS to_duration,
        f.tagline AS from_tagline,
        t.tagline AS to_tagline,
        CASE WHEN f.work_href IS NULL THEN NULL ELSE f.details_json END AS from_details_json,
        t.details_json AS to_details_json,
        CASE
            WHEN f.work_href IS NOT NULL
             AND t.work_href IS NOT NULL
             AND IFNULL(f.details_json, '{}') <> IFNULL(t.details_json, '{}') THEN 1
            ELSE 0
        END AS details_json_changed,
        CASE
            WHEN f.work_href IS NULL THEN 'added'
            WHEN t.work_href IS NULL THEN 'removed'
            WHEN IFNULL(f.title, '') <> IFNULL(t.title, '')
              OR IFNULL(f.release_date, '') <> IFNULL(t.release_date, '')
              OR IFNULL(f.metascore, '') <> IFNULL(t.metascore, '')
              OR IFNULL(f.user_score, '') <> IFNULL(t.user_score, '')
              OR IFNULL(f.rating, '') <> IFNULL(t.rating, '')
              OR IFNULL(f.duration, '') <> IFNULL(t.duration, '')
              OR IFNULL(f.tagline, '') <> IFNULL(t.tagline, '')
              OR IFNULL(f.details_json, '{}') <> IFNULL(t.details_json, '{}') THEN 'changed'
            ELSE 'unchanged'
        END AS change_type
    FROM to_snapshots t
    LEFT JOIN from_snapshots f
      ON f.work_href = t.work_href
    WHERE f.work_href IS NULL
)
SELECT
    work_href,
    category,
    from_title,
    to_title,
    from_release_date,
    to_release_date,
    from_metascore,
    to_metascore,
    from_user_score,
    to_user_score,
    from_rating,
    to_rating,
    from_duration,
    to_duration,
    from_tagline,
    to_tagline,
    from_details_json,
    to_details_json,
    details_json_changed,
    change_type
FROM compare_rows
WHERE ?1 = 1
   OR change_type <> 'unchanged'
ORDER BY category ASC, work_href ASC
`

type CompareWorkDetailSnapshotsParams struct {
	IncludeUnchanged interface{}
	FromRunID        string
	Category         interface{}
	WorkHref         interface{}
	ToRunID          string
}

type CompareWorkDetailSnapshotsRow struct {
	WorkHref           string
	Category           string
	FromTitle          interface{}
	ToTitle            sql.NullString
	FromReleaseDate    sql.NullString
	ToReleaseDate      sql.NullString
	FromMetascore      sql.NullString
	ToMetascore        sql.NullString
	FromUserScore      sql.NullString
	ToUserScore        sql.NullString
	FromRating         sql.NullString
	ToRating           sql.NullString
	FromDuration       sql.NullString
	ToDuration         sql.NullString
	FromTagline        sql.NullString
	ToTagline          sql.NullString
	FromDetailsJson    interface{}
	ToDetailsJson      sql.NullString
	DetailsJsonChanged int64
	ChangeType         string
}

func (q *Queries) CompareWorkDetailSnapshots(ctx context.Context, arg CompareWorkDetailSnapshotsParams) ([]CompareWorkDetailSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, compareWorkDetailSnapshots,
		arg.IncludeUnchanged,
		arg.FromRunID,
		arg.Category,
		arg.WorkHref,
		arg.ToRunID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompareWorkDetailSnapshotsRow
	for rows.Next() {
		var i CompareWorkDetailSnapshotsRow
		if err := rows.Scan(
			&i.WorkHref,
			&i.Category,
			&i.FromTitle,
			&i.ToTitle,
			&i.FromReleaseDate,
			&i.ToReleaseDate,
			&i.FromMetascore,
			&i.ToMetascore,
			&i.FromUserScore,
			&i.ToUserScore,
			&i.FromRating,
			&i.ToRating,
			&i.FromDuration,
			&i.ToDuration,
			&i.FromTagline,
			&i.ToTagline,
			&i.FromDetailsJson,
			&i.ToDetailsJson,
			&i.DetailsJsonChanged,
			&i.ChangeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWorkDetailSnapshots = `-- name: CountWorkDetailSnapshots :one
SELECT COUNT(*) FROM work_detail_snapshots
`

func (q *Queries) CountWorkDetailSnapshots(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkDetailSnapshots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkDetailSnapshotsByWorkHref = `-- name: CountWorkDetailSnapshotsByWorkHref :one
SELECT COUNT(*) FROM work_detail_snapshots WHERE work_href = ?
`

func (q *Queries) CountWorkDetailSnapshotsByWorkHref(ctx context.Context, workHref string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkDetailSnapshotsByWorkHref, workHref)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkDetails = `-- name: CountWorkDetails :one
SELECT COUNT(*) FROM work_details
`

func (q *Queries) CountWorkDetails(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkDetails)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDetailFetchState = `-- name: GetDetailFetchState :one
SELECT
    work_href,
    status,
    last_attempted_at,
    last_fetched_at,
    last_run_id,
    last_error,
    last_error_type,
    last_error_stage,
    updated_at
FROM detail_fetch_state
WHERE work_href = ? LIMIT 1
`

func (q *Queries) GetDetailFetchState(ctx context.Context, workHref string) (DetailFetchState, error) {
	row := q.db.QueryRowContext(ctx, getDetailFetchState, workHref)
	var i DetailFetchState
	err := row.Scan(
		&i.WorkHref,
		&i.Status,
		&i.LastAttemptedAt,
		&i.LastFetchedAt,
		&i.LastRunID,
		&i.LastError,
		&i.LastErrorType,
		&i.LastErrorStage,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkDetail = `-- name: GetWorkDetail :one
SELECT
    work_href,
    category,
    title,
    summary,
    release_date,
    metascore,
    metascore_sentiment,
    metascore_review_count,
    user_score,
    user_score_sentiment,
    user_score_count,
    rating,
    duration,
    tagline,
    details_json,
    last_fetched_at,
    created_at,
    updated_at
FROM work_details
WHERE RTRIM(work_href, '/') = RTRIM(?, '/') LIMIT 1
`

func (q *Queries) GetWorkDetail(ctx context.Context, rtrim string) (WorkDetail, error) {
	row := q.db.QueryRowContext(ctx, getWorkDetail, rtrim)
	var i WorkDetail
	err := row.Scan(
		&i.WorkHref,
		&i.Category,
		&i.Title,
		&i.Summary,
		&i.ReleaseDate,
		&i.Metascore,
		&i.MetascoreSentiment,
		&i.MetascoreReviewCount,
		&i.UserScore,
		&i.UserScoreSentiment,
		&i.UserScoreCount,
		&i.Rating,
		&i.Duration,
		&i.Tagline,
		&i.DetailsJson,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkDetailSnapshot = `-- name: InsertWorkDetailSnapshot :exec
INSERT INTO work_detail_snapshots (
    work_href,
    crawl_run_id,
    category,
    title,
    summary,
    release_date,
    metascore,
    metascore_sentiment,
    metascore_review_count,
    user_score,
    user_score_sentiment,
    user_score_count,
    rating,
    duration,
    tagline,
    details_json,
    fetched_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17
)
ON CONFLICT(work_href, crawl_run_id) DO NOTHING
`

type InsertWorkDetailSnapshotParams struct {
	WorkHref             string
	CrawlRunID           string
	Category             string
	Title                string
	Summary              sql.NullString
	ReleaseDate          sql.NullString
	Metascore            sql.NullString
	MetascoreSentiment   sql.NullString
	MetascoreReviewCount sql.NullInt64
	UserScore            sql.NullString
	UserScoreSentiment   sql.NullString
	UserScoreCount       sql.NullInt64
	Rating               sql.NullString
	Duration             sql.NullString
	Tagline              sql.NullString
	DetailsJson          string
	FetchedAt            string
}

func (q *Queries) InsertWorkDetailSnapshot(ctx context.Context, arg InsertWorkDetailSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkDetailSnapshot,
		arg.WorkHref,
		arg.CrawlRunID,
		arg.Category,
		arg.Title,
		arg.Summary,
		arg.ReleaseDate,
		arg.Metascore,
		arg.MetascoreSentiment,
		arg.MetascoreReviewCount,
		arg.UserScore,
		arg.UserScoreSentiment,
		arg.UserScoreCount,
		arg.Rating,
		arg.Duration,
		arg.Tagline,
		arg.DetailsJson,
		arg.FetchedAt,
	)
	return err
}

const listDetailCandidates = `-- name: ListDetailCandidates :many
SELECT
    w.href,
    w.name,
    w.image_url,
    w.release_date,
    w.category,
    w.created_at,
    w.updated_at,
    dfs.status AS fetch_status,
    dfs.last_attempted_at,
    dfs.last_fetched_at,
    dfs.last_run_id,
    dfs.last_error,
    dfs.last_error_type,
    dfs.last_error_stage,
    dfs.updated_at AS fetch_updated_at,
    wd.work_href IS NOT NULL AS has_detail
FROM works w
LEFT JOIN detail_fetch_state dfs ON dfs.work_href = w.href
LEFT JOIN work_details wd ON wd.work_href = w.href
WHERE (?1 = '' OR w.category = ?1)
  AND (?2 = '' OR RTRIM(w.href, '/') = RTRIM(?2, '/'))
  AND (
      ?3 = 1
      OR dfs.status IS NULL
      OR dfs.status <> 'succeeded'
      OR wd.work_href IS NULL
  )
ORDER BY w.category ASC, w.href ASC
LIMIT CASE WHEN ?4 <= 0 THEN -1 ELSE ?4 END
`

type ListDetailCandidatesParams struct {
	Category     interface{}
	WorkHref     interface{}
	ForceRefresh interface{}
	LimitRows    interface{}
}

type ListDetailCandidatesRow struct {
	Href            string
	Name            string
	ImageUrl        sql.NullString
	ReleaseDate     sql.NullString
	Category        string
	CreatedAt       string
	UpdatedAt       string
	FetchStatus     sql.NullString
	LastAttemptedAt sql.NullString
	LastFetchedAt   sql.NullString
	LastRunID       sql.NullString
	LastError       sql.NullString
	LastErrorType   sql.NullString
	LastErrorStage  sql.NullString
	FetchUpdatedAt  sql.NullString
	HasDetail       bool
}

func (q *Queries) ListDetailCandidates(ctx context.Context, arg ListDetailCandidatesParams) ([]ListDetailCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDetailCandidates,
		arg.Category,
		arg.WorkHref,
		arg.ForceRefresh,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDetailCandidatesRow
	for rows.Next() {
		var i ListDetailCandidatesRow
		if err := rows.Scan(
			&i.Href,
			&i.Name,
			&i.ImageUrl,
			&i.ReleaseDate,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FetchStatus,
			&i.LastAttemptedAt,
			&i.LastFetchedAt,
			&i.LastRunID,
			&i.LastError,
			&i.LastErrorType,
			&i.LastErrorStage,
			&i.FetchUpdatedAt,
			&i.HasDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkDetailSnapshotsByRun = `-- name: ListWorkDetailSnapshotsByRun :many
SELECT
    work_href,
    crawl_run_id,
    category,
    title,
    summary,
    release_date,
    metascore,
    metascore_sentiment,
    metascore_review_count,
    user_score,
    user_score_sentiment,
    user_score_count,
    rating,
    duration,
    tagline,
    details_json,
    fetched_at,
    created_at
FROM work_detail_snapshots
WHERE crawl_run_id = ?1
  AND (?2 = '' OR category = ?2)
  AND (?3 = '' OR RTRIM(work_href, '/') = RTRIM(?3, '/'))
ORDER BY category ASC, title ASC, work_href ASC
LIMIT CASE WHEN ?4 <= 0 THEN -1 ELSE ?4 END
`

type ListWorkDetailSnapshotsByRunParams struct {
	CrawlRunID string
	Category   interface{}
	WorkHref   interface{}
	LimitRows  interface{}
}

func (q *Queries) ListWorkDetailSnapshotsByRun(ctx context.Context, arg ListWorkDetailSnapshotsByRunParams) ([]WorkDetailSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listWorkDetailSnapshotsByRun,
		arg.CrawlRunID,
		arg.Category,
		arg.WorkHref,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkDetailSnapshot
	for rows.Next() {
		var i WorkDetailSnapshot
		if err := rows.Scan(
			&i.WorkHref,
			&i.CrawlRunID,
			&i.Category,
			&i.Title,
			&i.Summary,
			&i.ReleaseDate,
			&i.Metascore,
			&i.MetascoreSentiment,
			&i.MetascoreReviewCount,
			&i.UserScore,
			&i.UserScoreSentiment,
			&i.UserScoreCount,
			&i.Rating,
			&i.Duration,
			&i.Tagline,
			&i.DetailsJson,
			&i.FetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkDetails = `-- name: ListWorkDetails :many
SELECT
    work_href,
    category,
    title,
    summary,
    release_date,
    metascore,
    metascore_sentiment,
    metascore_review_count,
    user_score,
    user_score_sentiment,
    user_score_count,
    rating,
    duration,
    tagline,
    details_json,
    last_fetched_at,
    created_at,
    updated_at
FROM work_details
WHERE (?1 = '' OR category = ?1)
  AND (?2 = '' OR RTRIM(work_href, '/') = RTRIM(?2, '/'))
ORDER BY category ASC, title ASC, work_href ASC
LIMIT CASE WHEN ?3 <= 0 THEN -1 ELSE ?3 END
`

type ListWorkDetailsParams struct {
	Category  interface{}
	WorkHref  interface{}
	LimitRows interface{}
}

func (q *Queries) ListWorkDetails(ctx context.Context, arg ListWorkDetailsParams) ([]WorkDetail, error) {
	rows, err := q.db.QueryContext(ctx, listWorkDetails, arg.Category, arg.WorkHref, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkDetail
	for rows.Next() {
		var i WorkDetail
		if err := rows.Scan(
			&i.WorkHref,
			&i.Category,
			&i.Title,
			&i.Summary,
			&i.ReleaseDate,
			&i.Metascore,
			&i.MetascoreSentiment,
			&i.MetascoreReviewCount,
			&i.UserScore,
			&i.UserScoreSentiment,
			&i.UserScoreCount,
			&i.Rating,
			&i.Duration,
			&i.Tagline,
			&i.DetailsJson,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkDetailsForExport = `-- name: ListWorkDetailsForExport :many
SELECT
    wd.work_href,
    wd.category,
    wd.title,
    wd.summary,
    wd.release_date,
    wd.metascore,
    wd.metascore_sentiment,
    wd.metascore_review_count,
    wd.user_score,
    wd.user_score_sentiment,
    wd.user_score_count,
    wd.rating,
    wd.duration,
    wd.tagline,
    wd.details_json,
    wd.last_fetched_at,
    wd.created_at,
    wd.updated_at,
    COALESCE(dfs.last_run_id, '') AS source_run_id
FROM work_details wd
LEFT JOIN detail_fetch_state dfs ON dfs.work_href = wd.work_href
WHERE (?1 = '' OR wd.category = ?1)
  AND (?2 = '' OR RTRIM(wd.work_href, '/') = RTRIM(?2, '/'))
ORDER BY wd.category ASC, wd.title ASC, wd.work_href ASC
LIMIT CASE WHEN ?3 <= 0 THEN -1 ELSE ?3 END
`

type ListWorkDetailsForExportParams struct {
	Category  interface{}
	WorkHref  interface{}
	LimitRows interface{}
}

type ListWorkDetailsForExportRow struct {
	WorkHref             string
	Category             string
	Title                string
	Summary              sql.NullString
	ReleaseDate          sql.NullString
	Metascore            sql.NullString
	MetascoreSentiment   sql.NullString
	MetascoreReviewCount sql.NullInt64
	UserScore            sql.NullString
	UserScoreSentiment   sql.NullString
	UserScoreCount       sql.NullInt64
	Rating               sql.NullString
	Duration             sql.NullString
	Tagline              sql.NullString
	DetailsJson          string
	LastFetchedAt        string
	CreatedAt            string
	UpdatedAt            string
	SourceRunID          string
}

func (q *Queries) ListWorkDetailsForExport(ctx context.Context, arg ListWorkDetailsForExportParams) ([]ListWorkDetailsForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkDetailsForExport, arg.Category, arg.WorkHref, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkDetailsForExportRow
	for rows.Next() {
		var i ListWorkDetailsForExportRow
		if err := rows.Scan(
			&i.WorkHref,
			&i.Category,
			&i.Title,
			&i.Summary,
			&i.ReleaseDate,
			&i.Metascore,
			&i.MetascoreSentiment,
			&i.MetascoreReviewCount,
			&i.UserScore,
			&i.UserScoreSentiment,
			&i.UserScoreCount,
			&i.Rating,
			&i.Duration,
			&i.Tagline,
			&i.DetailsJson,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverStaleDetailFetchStates = `-- name: RecoverStaleDetailFetchStates :execrows
UPDATE detail_fetch_state
SET status = 'failed',
    last_run_id = ?1,
    last_error = 'recovered stale running state',
    last_error_type = 'state_recovered',
    last_error_stage = 'recovery',
    updated_at = ?2
WHERE status = 'running'
  AND (
      last_attempted_at IS NULL
      OR last_attempted_at = ''
      OR last_attempted_at <= ?3
  )
  AND work_href IN (
      SELECT href
      FROM works
      WHERE (?4 = '' OR category = ?4)
        AND (?5 = '' OR RTRIM(href, '/') = RTRIM(?5, '/'))
  )
`

type RecoverStaleDetailFetchStatesParams struct {
	LastRunID   sql.NullString
	UpdatedAt   string
	StaleBefore sql.NullString
	Category    interface{}
	WorkHref    interface{}
}

func (q *Queries) RecoverStaleDetailFetchStates(ctx context.Context, arg RecoverStaleDetailFetchStatesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverStaleDetailFetchStates,
		arg.LastRunID,
		arg.UpdatedAt,
		arg.StaleBefore,
		arg.Category,
		arg.WorkHref,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkFromDetail = `-- name: UpdateWorkFromDetail :exec
UPDATE works
SET name = CASE WHEN ?1 = '' THEN name ELSE ?1 END,
    release_date = CASE WHEN ?2 = '' THEN release_date ELSE ?2 END,
    category = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE href = ?4
`

type UpdateWorkFromDetailParams struct {
	Name        interface{}
	ReleaseDate interface{}
	Category    string
	Href        string
}

func (q *Queries) UpdateWorkFromDetail(ctx context.Context, arg UpdateWorkFromDetailParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkFromDetail,
		arg.Name,
		arg.ReleaseDate,
		arg.Category,
		arg.Href,
	)
	return err
}

const upsertDetailFetchStateFailed = `-- name: UpsertDetailFetchStateFailed :exec
INSERT INTO detail_fetch_state (
    work_href,
    status,
    last_attempted_at,
    last_fetched_at,
    last_run_id,
    last_error,
    last_error_type,
    last_error_stage,
    updated_at
) VALUES (
    ?1,
    'failed',
    ?2,
    NULL,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
ON CONFLICT(work_href) DO UPDATE SET
    status = 'failed',
    last_attempted_at = excluded.last_attempted_at,
    last_run_id = excluded.last_run_id,
    last_error = excluded.last_error,
    last_error_type = excluded.last_error_type,
    last_error_stage = excluded.last_error_stage,
    updated_at = excluded.updated_at
`

type UpsertDetailFetchStateFailedParams struct {
	WorkHref        string
	LastAttemptedAt sql.NullString
	LastRunID       sql.NullString
	LastError       sql.NullString
	LastErrorType   sql.NullString
	LastErrorStage  sql.NullString
	UpdatedAt       string
}

func (q *Queries) UpsertDetailFetchStateFailed(ctx context.Context, arg UpsertDetailFetchStateFailedParams) error {
	_, err := q.db.ExecContext(ctx, upsertDetailFetchStateFailed,
		arg.WorkHref,
		arg.LastAttemptedAt,
		arg.LastRunID,
		arg.LastError,
		arg.LastErrorType,
		arg.LastErrorStage,
		arg.UpdatedAt,
	)
	return err
}

const upsertDetailFetchStateRunning = `-- name: UpsertDetailFetchStateRunning :exec
INSERT INTO detail_fetch_state (
    work_href,
    status,
    last_attempted_at,
    last_fetched_at,
    last_run_id,
    last_error,
    last_error_type,
    last_error_stage,
    updated_at
) VALUES (
    ?1,
    'running',
    ?2,
    NULL,
    ?3,
    NULL,
    NULL,
    NULL,
    ?4
)
ON CONFLICT(work_href) DO UPDATE SET
    status = 'running',
    last_attempted_at = excluded.last_attempted_at,
    last_run_id = excluded.last_run_id,
    last_error = NULL,
    last_error_type = NULL,
    last_error_stage = NULL,
    updated_at = excluded.updated_at
`

type UpsertDetailFetchStateRunningParams struct {
	WorkHref        string
	LastAttemptedAt sql.NullString
	LastRunID       sql.NullString
	UpdatedAt       string
}

func (q *Queries) UpsertDetailFetchStateRunning(ctx context.Context, arg UpsertDetailFetchStateRunningParams) error {
	_, err := q.db.ExecContext(ctx, upsertDetailFetchStateRunning,
		arg.WorkHref,
		arg.LastAttemptedAt,
		arg.LastRunID,
		arg.UpdatedAt,
	)
	return err
}

const upsertDetailFetchStateSucceeded = `-- name: UpsertDetailFetchStateSucceeded :exec
INSERT INTO detail_fetch_state (
    work_href,
    status,
    last_attempted_at,
    last_fetched_at,
    last_run_id,
    last_error,
    last_error_type,
    last_error_stage,
    updated_at
) VALUES (
    ?1,
    'succeeded',
    ?2,
    ?3,
    ?4,
    NULL,
    NULL,
    NULL,
    ?5
)
ON CONFLICT(work_href) DO UPDATE SET
    status = 'succeeded',
    last_attempted_at = excluded.last_attempted_at,
    last_fetched_at = excluded.last_fetched_at,
    last_run_id = excluded.last_run_id,
    last_error = NULL,
    last_error_type = NULL,
    last_error_stage = NULL,
    updated_at = excluded.updated_at
`

type UpsertDetailFetchStateSucceededParams struct {
	WorkHref        string
	LastAttemptedAt sql.NullString
	LastFetchedAt   sql.NullString
	LastRunID       sql.NullString
	UpdatedAt       string
}

func (q *Queries) UpsertDetailFetchStateSucceeded(ctx context.Context, arg UpsertDetailFetchStateSucceededParams) error {
	_, err := q.db.ExecContext(ctx, upsertDetailFetchStateSucceeded,
		arg.WorkHref,
		arg.LastAttemptedAt,
		arg.LastFetchedAt,
		arg.LastRunID,
		arg.UpdatedAt,
	)
	return err
}

const upsertWorkDetail = `-- name: UpsertWorkDetail :exec
INSERT INTO work_details (
    work_href,
    category,
    title,
    summary,
    release_date,
    metascore,
    metascore_sentiment,
    metascore_review_count,
    user_score,
    user_score_sentiment,
    user_score_count,
    rating,
    duration,
    tagline,
    details_json,
    last_fetched_at,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT(work_href) DO UPDATE SET
    category = excluded.category,
    title = excluded.title,
    summary = excluded.summary,
    release_date = excluded.release_date,
    metascore = excluded.metascore,
    metascore_sentiment = excluded.metascore_sentiment,
    metascore_review_count = excluded.metascore_review_count,
    user_score = excluded.user_score,
    user_score_sentiment = excluded.user_score_sentiment,
    user_score_count = excluded.user_score_count,
    rating = excluded.rating,
    duration = excluded.duration,
    tagline = excluded.tagline,
    details_json = excluded.details_json,
    last_fetched_at = excluded.last_fetched_at,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertWorkDetailParams struct {
	WorkHref             string
	Category             string
	Title                string
	Summary              sql.NullString
	ReleaseDate          sql.NullString
	Metascore            sql.NullString
	MetascoreSentiment   sql.NullString
	MetascoreReviewCount sql.NullInt64
	UserScore            sql.NullString
	UserScoreSentiment   sql.NullString
	UserScoreCount       sql.NullInt64
	Rating               sql.NullString
	Duration             sql.NullString
	Tagline              sql.NullString
	DetailsJson          string
	LastFetchedAt        string
}

func (q *Queries) UpsertWorkDetail(ctx context.Context, arg UpsertWorkDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkDetail,
		arg.WorkHref,
		arg.Category,
		arg.Title,
		arg.Summary,
		arg.ReleaseDate,
		arg.Metascore,
		arg.MetascoreSentiment,
		arg.MetascoreReviewCount,
		arg.UserScore,
		arg.UserScoreSentiment,
		arg.UserScoreCount,
		arg.Rating,
		arg.Duration,
		arg.Tagline,
		arg.DetailsJson,
		arg.LastFetchedAt,
	)
	return err
}
