// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: list.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const compareCrawlRuns = `-- name: CompareCrawlRuns :many
WITH
from_entries AS (
    SELECT work_href, category, metric, filter_key, rank_no, metascore, user_score
    FROM list_entries le
    WHERE le.crawl_run_id = ?2
      AND (?3 = '' OR le.category = ?3)
      AND (?4 = '' OR le.metric = ?4)
),
to_entries AS (
    SELECT work_href, category, metric, filter_key, rank_no, metascore, user_score
    FROM list_entries le
    WHERE le.crawl_run_id = ?5
      AND (?3 = '' OR le.category = ?3)
      AND (?4 = '' OR le.metric = ?4)
),
compare_rows AS (
    SELECT
        COALESCE(f.work_href, t.work_href) AS work_href,
        COALESCE(f.category, t.category) AS category,
        COALESCE(f.metric, t.metric) AS metric,
        COALESCE(f.filter_key, t.filter_key) AS filter_key,
        IFNULL(f.rank_no, 0) AS from_rank,
        t.rank_no AS to_rank,
        CASE
            WHEN f.rank_no IS NOT NULL AND t.rank_no IS NOT NULL THEN t.rank_no - f.rank_no
            ELSE NULL
        END AS rank_diff,
        f.metascore AS from_metascore,
        t.metascore AS to_metascore,
        CASE
            WHEN f.metascore IS NOT NULL AND t.metascore IS NOT NULL THEN CAST(t.metascore AS REAL) - CAST(f.metascore AS REAL)
            ELSE NULL
        END AS metascore_diff,
        f.user_score AS from_user_score,
        t.user_score AS to_user_score,
        CASE
            WHEN f.user_score IS NOT NULL AND t.user_score IS NOT NULL THEN CAST(t.user_score AS REAL) - CAST(f.user_score AS REAL)
            ELSE NULL
        END AS user_score_diff,
        CASE
            WHEN f.work_href IS NULL THEN 'added'
            WHEN t.work_href IS NULL THEN 'removed'
            WHEN IFNULL(f.rank_no, -1) != IFNULL(t.rank_no, -1)
              OR IFNULL(f.metascore, '') != IFNULL(t.metascore, '')
              OR IFNULL(f.user_score, '') != IFNULL(t.user_score, '') THEN 'changed'
            ELSE 'unchanged'
        END AS change_type
    FROM from_entries f
    LEFT JOIN to_entries t
      ON f.work_href = t.work_href
     AND f.category = t.category
     AND f.metric = t.metric
     AND f.filter_key = t.filter_key

    UNION ALL

    SELECT
        COALESCE(f.work_href, t.work_href) AS work_href,
        COALESCE(f.category, t.category) AS category,
        COALESCE(f.metric, t.metric) AS metric,
        COALESCE(f.filter_key, t.filter_key) AS filter_key,
        IFNULL(f.rank_no, 0) AS from_rank,
        t.rank_no AS to_rank,
        CASE
            WHEN f.rank_no IS NOT NULL AND t.rank_no IS NOT NULL THEN t.rank_no - f.rank_no
            ELSE NULL
        END AS rank_diff,
        f.metascore AS from_metascore,
        t.metascore AS to_metascore,
        CASE
            WHEN f.metascore IS NOT NULL AND t.metascore IS NOT NULL THEN CAST(t.metascore AS REAL) - CAST(f.metascore AS REAL)
            ELSE NULL
        END AS metascore_diff,
        f.user_score AS from_user_score,
        t.user_score AS to_user_score,
        CASE
            WHEN f.user_score IS NOT NULL AND t.user_score IS NOT NULL THEN CAST(t.user_score AS REAL) - CAST(f.user_score AS REAL)
            ELSE NULL
        END AS user_score_diff,
        CASE
            WHEN f.work_href IS NULL THEN 'added'
            WHEN t.work_href IS NULL THEN 'removed'
            WHEN IFNULL(f.rank_no, -1) != IFNULL(t.rank_no, -1)
              OR IFNULL(f.metascore, '') != IFNULL(t.metascore, '')
              OR IFNULL(f.user_score, '') != IFNULL(t.user_score, '') THEN 'changed'
            ELSE 'unchanged'
        END AS change_type
    FROM to_entries t
    LEFT JOIN from_entries f
      ON f.work_href = t.work_href
     AND f.category = t.category
     AND f.metric = t.metric
     AND f.filter_key = t.filter_key
    WHERE f.work_href IS NULL
)
SELECT work_href, category, metric, filter_key, from_rank, to_rank, rank_diff, from_metascore, to_metascore, metascore_diff, from_user_score, to_user_score, user_score_diff, change_type
FROM compare_rows
WHERE (?1 = 1 OR change_type <> 'unchanged')
ORDER BY category ASC, metric ASC, filter_key ASC, change_type ASC, work_href ASC
`

type CompareCrawlRunsParams struct {
	IncludeUnchanged interface{}
	FromRunID        string
	Category         interface{}
	Metric           interface{}
	ToRunID          string
}

type CompareCrawlRunsRow struct {
	WorkHref      string
	Category      string
	Metric        string
	FilterKey     string
	FromRank      interface{}
	ToRank        sql.NullInt64
	RankDiff      interface{}
	FromMetascore sql.NullString
	ToMetascore   sql.NullString
	MetascoreDiff interface{}
	FromUserScore sql.NullString
	ToUserScore   sql.NullString
	UserScoreDiff interface{}
	ChangeType    string
}

func (q *Queries) CompareCrawlRuns(ctx context.Context, arg CompareCrawlRunsParams) ([]CompareCrawlRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, compareCrawlRuns,
		arg.IncludeUnchanged,
		arg.FromRunID,
		arg.Category,
		arg.Metric,
		arg.ToRunID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompareCrawlRunsRow
	for rows.Next() {
		var i CompareCrawlRunsRow
		if err := rows.Scan(
			&i.WorkHref,
			&i.Category,
			&i.Metric,
			&i.FilterKey,
			&i.FromRank,
			&i.ToRank,
			&i.RankDiff,
			&i.FromMetascore,
			&i.ToMetascore,
			&i.MetascoreDiff,
			&i.FromUserScore,
			&i.ToUserScore,
			&i.UserScoreDiff,
			&i.ChangeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeCrawlRun = `-- name: CompleteCrawlRun :exec
UPDATE crawl_runs
SET finished_at = ?1,
    status = ?2,
    error_message = NULL
WHERE run_id = ?3
`

type CompleteCrawlRunParams struct {
	FinishedAt sql.NullString
	Status     string
	RunID      string
}

func (q *Queries) CompleteCrawlRun(ctx context.Context, arg CompleteCrawlRunParams) error {
	_, err := q.db.ExecContext(ctx, completeCrawlRun, arg.FinishedAt, arg.Status, arg.RunID)
	return err
}

const countCrawlRuns = `-- name: CountCrawlRuns :one
SELECT COUNT(*) FROM crawl_runs
`

func (q *Queries) CountCrawlRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCrawlRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLatestListEntries = `-- name: CountLatestListEntries :one
SELECT COUNT(*) FROM latest_list_entries
`

func (q *Queries) CountLatestListEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLatestListEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListEntries = `-- name: CountListEntries :one
SELECT COUNT(*) FROM list_entries
`

func (q *Queries) CountListEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countListEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorks = `-- name: CountWorks :one
SELECT COUNT(*) FROM works
`

func (q *Queries) CountWorks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCrawlRun = `-- name: CreateCrawlRun :exec
INSERT INTO crawl_runs (
    run_id,
    source,
    task_name,
    category,
    metric,
    filter_key,
    started_at,
    status,
    error_message
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type CreateCrawlRunParams struct {
	RunID        string
	Source       string
	TaskName     string
	Category     string
	Metric       string
	FilterKey    string
	StartedAt    string
	Status       string
	ErrorMessage sql.NullString
}

func (q *Queries) CreateCrawlRun(ctx context.Context, arg CreateCrawlRunParams) error {
	_, err := q.db.ExecContext(ctx, createCrawlRun,
		arg.RunID,
		arg.Source,
		arg.TaskName,
		arg.Category,
		arg.Metric,
		arg.FilterKey,
		arg.StartedAt,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}

const failCrawlRun = `-- name: FailCrawlRun :exec
UPDATE crawl_runs
SET finished_at = ?1,
    status = ?2,
    error_message = ?3
WHERE run_id = ?4
`

type FailCrawlRunParams struct {
	FinishedAt   sql.NullString
	Status       string
	ErrorMessage sql.NullString
	RunID        string
}

func (q *Queries) FailCrawlRun(ctx context.Context, arg FailCrawlRunParams) error {
	_, err := q.db.ExecContext(ctx, failCrawlRun,
		arg.FinishedAt,
		arg.Status,
		arg.ErrorMessage,
		arg.RunID,
	)
	return err
}

const getCrawlRun = `-- name: GetCrawlRun :one
SELECT run_id, source, task_name, category, metric, filter_key, started_at, finished_at, status, error_message
FROM crawl_runs
WHERE run_id = ? LIMIT 1
`

func (q *Queries) GetCrawlRun(ctx context.Context, runID string) (CrawlRun, error) {
	row := q.db.QueryRowContext(ctx, getCrawlRun, runID)
	var i CrawlRun
	err := row.Scan(
		&i.RunID,
		&i.Source,
		&i.TaskName,
		&i.Category,
		&i.Metric,
		&i.FilterKey,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const getLatestEntryByWork = `-- name: GetLatestEntryByWork :many
SELECT work_href, category, metric, filter_key, page_no, rank_no, metascore, user_score, source_crawl_run_id, last_crawled_at, created_at, updated_at
FROM latest_list_entries
WHERE work_href = ?1
  AND (?2 = '' OR category = ?2)
  AND (?3 = '' OR metric = ?3)
ORDER BY category ASC, metric ASC, rank_no ASC
`

type GetLatestEntryByWorkParams struct {
	WorkHref string
	Category interface{}
	Metric   interface{}
}

func (q *Queries) GetLatestEntryByWork(ctx context.Context, arg GetLatestEntryByWorkParams) ([]LatestListEntry, error) {
	rows, err := q.db.QueryContext(ctx, getLatestEntryByWork, arg.WorkHref, arg.Category, arg.Metric)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestListEntry
	for rows.Next() {
		var i LatestListEntry
		if err := rows.Scan(
			&i.WorkHref,
			&i.Category,
			&i.Metric,
			&i.FilterKey,
			&i.PageNo,
			&i.RankNo,
			&i.Metascore,
			&i.UserScore,
			&i.SourceCrawlRunID,
			&i.LastCrawledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestListEntry = `-- name: GetLatestListEntry :one
SELECT work_href, category, metric, filter_key, page_no, rank_no, metascore, user_score, source_crawl_run_id, last_crawled_at, created_at, updated_at
FROM latest_list_entries
WHERE work_href = ? AND category = ? AND metric = ? AND filter_key = ?
LIMIT 1
`

type GetLatestListEntryParams struct {
	WorkHref  string
	Category  string
	Metric    string
	FilterKey string
}

func (q *Queries) GetLatestListEntry(ctx context.Context, arg GetLatestListEntryParams) (LatestListEntry, error) {
	row := q.db.QueryRowContext(ctx, getLatestListEntry,
		arg.WorkHref,
		arg.Category,
		arg.Metric,
		arg.FilterKey,
	)
	var i LatestListEntry
	err := row.Scan(
		&i.WorkHref,
		&i.Category,
		&i.Metric,
		&i.FilterKey,
		&i.PageNo,
		&i.RankNo,
		&i.Metascore,
		&i.UserScore,
		&i.SourceCrawlRunID,
		&i.LastCrawledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkByHref = `-- name: GetWorkByHref :one
SELECT href, name, image_url, release_date, category, created_at, updated_at
FROM works
WHERE href = ? LIMIT 1
`

func (q *Queries) GetWorkByHref(ctx context.Context, href string) (Work, error) {
	row := q.db.QueryRowContext(ctx, getWorkByHref, href)
	var i Work
	err := row.Scan(
		&i.Href,
		&i.Name,
		&i.ImageUrl,
		&i.ReleaseDate,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertListEntry = `-- name: InsertListEntry :exec
INSERT INTO list_entries (
    crawl_run_id,
    work_href,
    category,
    metric,
    page_no,
    rank_no,
    metascore,
    user_score,
    filter_key,
    crawled_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
`

type InsertListEntryParams struct {
	CrawlRunID string
	WorkHref   string
	Category   string
	Metric     string
	PageNo     int64
	RankNo     int64
	Metascore  sql.NullString
	UserScore  sql.NullString
	FilterKey  string
	CrawledAt  string
}

func (q *Queries) InsertListEntry(ctx context.Context, arg InsertListEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertListEntry,
		arg.CrawlRunID,
		arg.WorkHref,
		arg.Category,
		arg.Metric,
		arg.PageNo,
		arg.RankNo,
		arg.Metascore,
		arg.UserScore,
		arg.FilterKey,
		arg.CrawledAt,
	)
	return err
}

const listCrawlRuns = `-- name: ListCrawlRuns :many
SELECT run_id, source, task_name, category, metric, filter_key, started_at, finished_at, status, error_message
FROM crawl_runs
ORDER BY started_at DESC
LIMIT CASE WHEN ?1 <= 0 THEN -1 ELSE ?1 END
`

func (q *Queries) ListCrawlRuns(ctx context.Context, limitRows interface{}) ([]CrawlRun, error) {
	rows, err := q.db.QueryContext(ctx, listCrawlRuns, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrawlRun
	for rows.Next() {
		var i CrawlRun
		if err := rows.Scan(
			&i.RunID,
			&i.Source,
			&i.TaskName,
			&i.Category,
			&i.Metric,
			&i.FilterKey,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestEntries = `-- name: ListLatestEntries :many
SELECT work_href, category, metric, filter_key, page_no, rank_no, metascore, user_score, source_crawl_run_id, last_crawled_at, created_at, updated_at
FROM latest_list_entries
WHERE (?1 = '' OR category = ?1)
  AND (?2 = '' OR metric = ?2)
  AND (?3 = '' OR work_href = ?3)
  AND (?4 = '' OR filter_key = ?4)
ORDER BY category ASC, metric ASC, rank_no ASC, work_href ASC
LIMIT CASE WHEN ?5 <= 0 THEN -1 ELSE ?5 END
`

type ListLatestEntriesParams struct {
	Category  interface{}
	Metric    interface{}
	WorkHref  interface{}
	FilterKey interface{}
	LimitRows interface{}
}

func (q *Queries) ListLatestEntries(ctx context.Context, arg ListLatestEntriesParams) ([]LatestListEntry, error) {
	rows, err := q.db.QueryContext(ctx, listLatestEntries,
		arg.Category,
		arg.Metric,
		arg.WorkHref,
		arg.FilterKey,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestListEntry
	for rows.Next() {
		var i LatestListEntry
		if err := rows.Scan(
			&i.WorkHref,
			&i.Category,
			&i.Metric,
			&i.FilterKey,
			&i.PageNo,
			&i.RankNo,
			&i.Metascore,
			&i.UserScore,
			&i.SourceCrawlRunID,
			&i.LastCrawledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLatestListEntry = `-- name: UpsertLatestListEntry :exec
INSERT INTO latest_list_entries (
    work_href,
    category,
    metric,
    filter_key,
    page_no,
    rank_no,
    metascore,
    user_score,
    source_crawl_run_id,
    last_crawled_at,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT(work_href, category, metric, filter_key) DO UPDATE SET
    page_no = excluded.page_no,
    rank_no = excluded.rank_no,
    metascore = excluded.metascore,
    user_score = excluded.user_score,
    source_crawl_run_id = excluded.source_crawl_run_id,
    last_crawled_at = excluded.last_crawled_at,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertLatestListEntryParams struct {
	WorkHref         string
	Category         string
	Metric           string
	FilterKey        string
	PageNo           int64
	RankNo           int64
	Metascore        sql.NullString
	UserScore        sql.NullString
	SourceCrawlRunID string
	LastCrawledAt    string
}

func (q *Queries) UpsertLatestListEntry(ctx context.Context, arg UpsertLatestListEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertLatestListEntry,
		arg.WorkHref,
		arg.Category,
		arg.Metric,
		arg.FilterKey,
		arg.PageNo,
		arg.RankNo,
		arg.Metascore,
		arg.UserScore,
		arg.SourceCrawlRunID,
		arg.LastCrawledAt,
	)
	return err
}

const upsertWork = `-- name: UpsertWork :exec
INSERT INTO works (
    href,
    name,
    image_url,
    release_date,
    category,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT(href) DO UPDATE SET
    name = excluded.name,
    image_url = excluded.image_url,
    release_date = excluded.release_date,
    category = excluded.category,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertWorkParams struct {
	Href        string
	Name        string
	ImageUrl    sql.NullString
	ReleaseDate sql.NullString
	Category    string
}

func (q *Queries) UpsertWork(ctx context.Context, arg UpsertWorkParams) error {
	_, err := q.db.ExecContext(ctx, upsertWork,
		arg.Href,
		arg.Name,
		arg.ImageUrl,
		arg.ReleaseDate,
		arg.Category,
	)
	return err
}
