// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type CrawlRun struct {
	RunID        string
	Source       string
	TaskName     string
	Category     string
	Metric       string
	FilterKey    string
	StartedAt    string
	FinishedAt   sql.NullString
	Status       string
	ErrorMessage sql.NullString
}

type DetailFetchState struct {
	WorkHref        string
	Status          string
	LastAttemptedAt sql.NullString
	LastFetchedAt   sql.NullString
	LastRunID       sql.NullString
	LastError       sql.NullString
	LastErrorType   sql.NullString
	LastErrorStage  sql.NullString
	UpdatedAt       string
}

type LatestListEntry struct {
	WorkHref         string
	Category         string
	Metric           string
	FilterKey        string
	PageNo           int64
	RankNo           int64
	Metascore        sql.NullString
	UserScore        sql.NullString
	SourceCrawlRunID string
	LastCrawledAt    string
	CreatedAt        string
	UpdatedAt        string
}

type LatestReview struct {
	ReviewKey         string
	ExternalReviewID  sql.NullString
	WorkHref          string
	Category          string
	ReviewType        string
	PlatformKey       string
	ReviewUrl         sql.NullString
	ReviewDate        sql.NullString
	Score             sql.NullFloat64
	Quote             sql.NullString
	PublicationName   sql.NullString
	PublicationSlug   sql.NullString
	AuthorName        sql.NullString
	AuthorSlug        sql.NullString
	SeasonLabel       sql.NullString
	Username          sql.NullString
	UserSlug          sql.NullString
	ThumbsUp          sql.NullInt64
	ThumbsDown        sql.NullInt64
	VersionLabel      sql.NullString
	SpoilerFlag       sql.NullInt64
	SourcePayloadJson string
	SourceCrawlRunID  string
	LastCrawledAt     string
	CreatedAt         string
	UpdatedAt         string
}

type ListEntry struct {
	ID         int64
	CrawlRunID string
	WorkHref   string
	Category   string
	Metric     string
	PageNo     int64
	RankNo     int64
	Metascore  sql.NullString
	UserScore  sql.NullString
	FilterKey  string
	CrawledAt  string
}

type ReviewFetchState struct {
	WorkHref        string
	ReviewType      string
	PlatformKey     string
	Status          string
	LastAttemptedAt sql.NullString
	LastFetchedAt   sql.NullString
	LastRunID       sql.NullString
	LastError       sql.NullString
	LastErrorType   sql.NullString
	LastErrorStage  sql.NullString
	UpdatedAt       string
}

type ReviewSnapshot struct {
	ReviewKey         string
	CrawlRunID        string
	ExternalReviewID  sql.NullString
	WorkHref          string
	Category          string
	ReviewType        string
	PlatformKey       string
	ReviewUrl         sql.NullString
	ReviewDate        sql.NullString
	Score             sql.NullFloat64
	Quote             sql.NullString
	PublicationName   sql.NullString
	PublicationSlug   sql.NullString
	AuthorName        sql.NullString
	AuthorSlug        sql.NullString
	SeasonLabel       sql.NullString
	Username          sql.NullString
	UserSlug          sql.NullString
	ThumbsUp          sql.NullInt64
	ThumbsDown        sql.NullInt64
	VersionLabel      sql.NullString
	SpoilerFlag       sql.NullInt64
	SourcePayloadJson string
	CrawledAt         string
	CreatedAt         string
}

type Work struct {
	Href        string
	Name        string
	ImageUrl    sql.NullString
	ReleaseDate sql.NullString
	Category    string
	CreatedAt   string
	UpdatedAt   string
}

type WorkDetail struct {
	WorkHref             string
	Category             string
	Title                string
	Summary              sql.NullString
	ReleaseDate          sql.NullString
	Metascore            sql.NullString
	MetascoreSentiment   sql.NullString
	MetascoreReviewCount sql.NullInt64
	UserScore            sql.NullString
	UserScoreSentiment   sql.NullString
	UserScoreCount       sql.NullInt64
	Rating               sql.NullString
	Duration             sql.NullString
	Tagline              sql.NullString
	DetailsJson          string
	LastFetchedAt        string
	CreatedAt            string
	UpdatedAt            string
}

type WorkDetailSnapshot struct {
	WorkHref             string
	CrawlRunID           string
	Category             string
	Title                string
	Summary              sql.NullString
	ReleaseDate          sql.NullString
	Metascore            sql.NullString
	MetascoreSentiment   sql.NullString
	MetascoreReviewCount sql.NullInt64
	UserScore            sql.NullString
	UserScoreSentiment   sql.NullString
	UserScoreCount       sql.NullInt64
	Rating               sql.NullString
	Duration             sql.NullString
	Tagline              sql.NullString
	DetailsJson          string
	FetchedAt            string
	CreatedAt            string
}
