// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: reviews.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const compareReviewSnapshots = `-- name: CompareReviewSnapshots :many
WITH
from_reviews AS (
    SELECT
        rs.review_key,
        rs.work_href,
        rs.category,
        rs.review_type,
        rs.platform_key,
        rs.score,
        rs.quote,
        rs.thumbs_up,
        rs.thumbs_down,
        rs.version_label,
        rs.spoiler_flag
    FROM review_snapshots rs
    WHERE rs.crawl_run_id = ?2
      AND (?3 = '' OR rs.category = ?3)
      AND (?4 = '' OR rs.review_type = ?4)
      AND (?5 = '' OR rs.platform_key = ?5)
      AND (?6 = '' OR RTRIM(rs.work_href, '/') = RTRIM(?6, '/'))
),
to_reviews AS (
    SELECT
        rs.review_key,
        rs.work_href,
        rs.category,
        rs.review_type,
        rs.platform_key,
        rs.score,
        rs.quote,
        rs.thumbs_up,
        rs.thumbs_down,
        rs.version_label,
        rs.spoiler_flag
    FROM review_snapshots rs
    WHERE rs.crawl_run_id = ?7
      AND (?3 = '' OR rs.category = ?3)
      AND (?4 = '' OR rs.review_type = ?4)
      AND (?5 = '' OR rs.platform_key = ?5)
      AND (?6 = '' OR RTRIM(rs.work_href, '/') = RTRIM(?6, '/'))
),
compare_rows AS (
    SELECT
        COALESCE(f.review_key, t.review_key) AS review_key,
        COALESCE(f.work_href, t.work_href) AS work_href,
        COALESCE(f.category, t.category) AS category,
        COALESCE(f.review_type, t.review_type) AS review_type,
        COALESCE(f.platform_key, t.platform_key) AS platform_key,
        f.score AS from_score,
        t.score AS to_score,
        CASE
            WHEN f.score IS NOT NULL AND t.score IS NOT NULL THEN t.score - f.score
            ELSE NULL
        END AS score_diff,
        f.quote AS from_quote,
        t.quote AS to_quote,
        f.thumbs_up AS from_thumbs_up,
        t.thumbs_up AS to_thumbs_up,
        f.thumbs_down AS from_thumbs_down,
        t.thumbs_down AS to_thumbs_down,
        f.version_label AS from_version_label,
        t.version_label AS to_version_label,
        f.spoiler_flag AS from_spoiler_flag,
        t.spoiler_flag AS to_spoiler_flag,
        CASE
            WHEN f.review_key IS NULL THEN 'added'
            WHEN t.review_key IS NULL THEN 'removed'
            WHEN IFNULL(f.score, -999999) <> IFNULL(t.score, -999999)
              OR IFNULL(f.quote, '') <> IFNULL(t.quote, '')
              OR IFNULL(f.thumbs_up, -1) <> IFNULL(t.thumbs_up, -1)
              OR IFNULL(f.thumbs_down, -1) <> IFNULL(t.thumbs_down, -1)
              OR IFNULL(f.version_label, '') <> IFNULL(t.version_label, '')
              OR IFNULL(f.spoiler_flag, -1) <> IFNULL(t.spoiler_flag, -1) THEN 'changed'
            ELSE 'unchanged'
        END AS change_type
    FROM from_reviews f
    LEFT JOIN to_reviews t ON f.review_key = t.review_key

    UNION ALL

    SELECT
        COALESCE(f.review_key, t.review_key) AS review_key,
        COALESCE(f.work_href, t.work_href) AS work_href,
        COALESCE(f.category, t.category) AS category,
        COALESCE(f.review_type, t.review_type) AS review_type,
        COALESCE(f.platform_key, t.platform_key) AS platform_key,
        f.score AS from_score,
        t.score AS to_score,
        CASE
            WHEN f.score IS NOT NULL AND t.score IS NOT NULL THEN t.score - f.score
            ELSE NULL
        END AS score_diff,
        f.quote AS from_quote,
        t.quote AS to_quote,
        f.thumbs_up AS from_thumbs_up,
        t.thumbs_up AS to_thumbs_up,
        f.thumbs_down AS from_thumbs_down,
        t.thumbs_down AS to_thumbs_down,
        f.version_label AS from_version_label,
        t.version_label AS to_version_label,
        f.spoiler_flag AS from_spoiler_flag,
        t.spoiler_flag AS to_spoiler_flag,
        CASE
            WHEN f.review_key IS NULL THEN 'added'
            WHEN t.review_key IS NULL THEN 'removed'
            WHEN IFNULL(f.score, -999999) <> IFNULL(t.score, -999999)
              OR IFNULL(f.quote, '') <> IFNULL(t.quote, '')
              OR IFNULL(f.thumbs_up, -1) <> IFNULL(t.thumbs_up, -1)
              OR IFNULL(f.thumbs_down, -1) <> IFNULL(t.thumbs_down, -1)
              OR IFNULL(f.version_label, '') <> IFNULL(t.version_label, '')
              OR IFNULL(f.spoiler_flag, -1) <> IFNULL(t.spoiler_flag, -1) THEN 'changed'
            ELSE 'unchanged'
        END AS change_type
    FROM to_reviews t
    LEFT JOIN from_reviews f ON f.review_key = t.review_key
    WHERE f.review_key IS NULL
)
SELECT
    review_key,
    work_href,
    category,
    review_type,
    platform_key,
    from_score,
    to_score,
    score_diff,
    from_quote,
    to_quote,
    from_thumbs_up,
    to_thumbs_up,
    from_thumbs_down,
    to_thumbs_down,
    from_version_label,
    to_version_label,
    from_spoiler_flag,
    to_spoiler_flag,
    change_type
FROM compare_rows
WHERE ?1 = 1
   OR change_type <> 'unchanged'
ORDER BY category ASC, review_type ASC, platform_key ASC, change_type ASC, work_href ASC, review_key ASC
`

type CompareReviewSnapshotsParams struct {
	IncludeUnchanged interface{}
	FromRunID        string
	Category         interface{}
	ReviewType       interface{}
	PlatformKey      interface{}
	WorkHref         interface{}
	ToRunID          string
}

type CompareReviewSnapshotsRow struct {
	ReviewKey        string
	WorkHref         string
	Category         string
	ReviewType       string
	PlatformKey      string
	FromScore        sql.NullFloat64
	ToScore          sql.NullFloat64
	ScoreDiff        interface{}
	FromQuote        sql.NullString
	ToQuote          sql.NullString
	FromThumbsUp     sql.NullInt64
	ToThumbsUp       sql.NullInt64
	FromThumbsDown   sql.NullInt64
	ToThumbsDown     sql.NullInt64
	FromVersionLabel sql.NullString
	ToVersionLabel   sql.NullString
	FromSpoilerFlag  sql.NullInt64
	ToSpoilerFlag    sql.NullInt64
	ChangeType       string
}

func (q *Queries) CompareReviewSnapshots(ctx context.Context, arg CompareReviewSnapshotsParams) ([]CompareReviewSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, compareReviewSnapshots,
		arg.IncludeUnchanged,
		arg.FromRunID,
		arg.Category,
		arg.ReviewType,
		arg.PlatformKey,
		arg.WorkHref,
		arg.ToRunID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompareReviewSnapshotsRow
	for rows.Next() {
		var i CompareReviewSnapshotsRow
		if err := rows.Scan(
			&i.ReviewKey,
			&i.WorkHref,
			&i.Category,
			&i.ReviewType,
			&i.PlatformKey,
			&i.FromScore,
			&i.ToScore,
			&i.ScoreDiff,
			&i.FromQuote,
			&i.ToQuote,
			&i.FromThumbsUp,
			&i.ToThumbsUp,
			&i.FromThumbsDown,
			&i.ToThumbsDown,
			&i.FromVersionLabel,
			&i.ToVersionLabel,
			&i.FromSpoilerFlag,
			&i.ToSpoilerFlag,
			&i.ChangeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLatestReviews = `-- name: CountLatestReviews :one
SELECT COUNT(*) FROM latest_reviews
`

func (q *Queries) CountLatestReviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLatestReviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewSnapshots = `-- name: CountReviewSnapshots :one
SELECT COUNT(*) FROM review_snapshots
`

func (q *Queries) CountReviewSnapshots(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewSnapshots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReviewFetchState = `-- name: GetReviewFetchState :one
SELECT
    work_href,
    review_type,
    platform_key,
    status,
    last_attempted_at,
    last_fetched_at,
    last_run_id,
    last_error,
    last_error_type,
    last_error_stage,
    updated_at
FROM review_fetch_state
WHERE RTRIM(work_href, '/') = RTRIM(?1, '/')
  AND review_type = ?2
  AND platform_key = ?3
LIMIT 1
`

type GetReviewFetchStateParams struct {
	WorkHref    string
	ReviewType  string
	PlatformKey string
}

func (q *Queries) GetReviewFetchState(ctx context.Context, arg GetReviewFetchStateParams) (ReviewFetchState, error) {
	row := q.db.QueryRowContext(ctx, getReviewFetchState, arg.WorkHref, arg.ReviewType, arg.PlatformKey)
	var i ReviewFetchState
	err := row.Scan(
		&i.WorkHref,
		&i.ReviewType,
		&i.PlatformKey,
		&i.Status,
		&i.LastAttemptedAt,
		&i.LastFetchedAt,
		&i.LastRunID,
		&i.LastError,
		&i.LastErrorType,
		&i.LastErrorStage,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReviewSnapshot = `-- name: InsertReviewSnapshot :exec
INSERT INTO review_snapshots (
    review_key,
    crawl_run_id,
    external_review_id,
    work_href,
    category,
    review_type,
    platform_key,
    review_url,
    review_date,
    score,
    quote,
    publication_name,
    publication_slug,
    author_name,
    author_slug,
    season_label,
    username,
    user_slug,
    thumbs_up,
    thumbs_down,
    version_label,
    spoiler_flag,
    source_payload_json,
    crawled_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19,
    ?20,
    ?21,
    ?22,
    ?23,
    ?24
)
ON CONFLICT(review_key, crawl_run_id) DO NOTHING
`

type InsertReviewSnapshotParams struct {
	ReviewKey         string
	CrawlRunID        string
	ExternalReviewID  sql.NullString
	WorkHref          string
	Category          string
	ReviewType        string
	PlatformKey       string
	ReviewUrl         sql.NullString
	ReviewDate        sql.NullString
	Score             sql.NullFloat64
	Quote             sql.NullString
	PublicationName   sql.NullString
	PublicationSlug   sql.NullString
	AuthorName        sql.NullString
	AuthorSlug        sql.NullString
	SeasonLabel       sql.NullString
	Username          sql.NullString
	UserSlug          sql.NullString
	ThumbsUp          sql.NullInt64
	ThumbsDown        sql.NullInt64
	VersionLabel      sql.NullString
	SpoilerFlag       sql.NullInt64
	SourcePayloadJson string
	CrawledAt         string
}

func (q *Queries) InsertReviewSnapshot(ctx context.Context, arg InsertReviewSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewSnapshot,
		arg.ReviewKey,
		arg.CrawlRunID,
		arg.ExternalReviewID,
		arg.WorkHref,
		arg.Category,
		arg.ReviewType,
		arg.PlatformKey,
		arg.ReviewUrl,
		arg.ReviewDate,
		arg.Score,
		arg.Quote,
		arg.PublicationName,
		arg.PublicationSlug,
		arg.AuthorName,
		arg.AuthorSlug,
		arg.SeasonLabel,
		arg.Username,
		arg.UserSlug,
		arg.ThumbsUp,
		arg.ThumbsDown,
		arg.VersionLabel,
		arg.SpoilerFlag,
		arg.SourcePayloadJson,
		arg.CrawledAt,
	)
	return err
}

const listLatestReviews = `-- name: ListLatestReviews :many
SELECT
    review_key,
    external_review_id,
    work_href,
    category,
    review_type,
    platform_key,
    review_url,
    review_date,
    score,
    quote,
    publication_name,
    publication_slug,
    author_name,
    author_slug,
    season_label,
    username,
    user_slug,
    thumbs_up,
    thumbs_down,
    version_label,
    spoiler_flag,
    source_payload_json,
    source_crawl_run_id,
    last_crawled_at,
    created_at,
    updated_at
FROM latest_reviews
WHERE (?1 = '' OR category = ?1)
  AND (?2 = '' OR review_type = ?2)
  AND (?3 = '' OR platform_key = ?3)
  AND (?4 = '' OR RTRIM(work_href, '/') = RTRIM(?4, '/'))
ORDER BY category ASC, review_type ASC, platform_key ASC, last_crawled_at DESC, review_key ASC
LIMIT CASE WHEN ?5 <= 0 THEN -1 ELSE ?5 END
`

type ListLatestReviewsParams struct {
	Category    interface{}
	ReviewType  interface{}
	PlatformKey interface{}
	WorkHref    interface{}
	LimitRows   interface{}
}

func (q *Queries) ListLatestReviews(ctx context.Context, arg ListLatestReviewsParams) ([]LatestReview, error) {
	rows, err := q.db.QueryContext(ctx, listLatestReviews,
		arg.Category,
		arg.ReviewType,
		arg.PlatformKey,
		arg.WorkHref,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestReview
	for rows.Next() {
		var i LatestReview
		if err := rows.Scan(
			&i.ReviewKey,
			&i.ExternalReviewID,
			&i.WorkHref,
			&i.Category,
			&i.ReviewType,
			&i.PlatformKey,
			&i.ReviewUrl,
			&i.ReviewDate,
			&i.Score,
			&i.Quote,
			&i.PublicationName,
			&i.PublicationSlug,
			&i.AuthorName,
			&i.AuthorSlug,
			&i.SeasonLabel,
			&i.Username,
			&i.UserSlug,
			&i.ThumbsUp,
			&i.ThumbsDown,
			&i.VersionLabel,
			&i.SpoilerFlag,
			&i.SourcePayloadJson,
			&i.SourceCrawlRunID,
			&i.LastCrawledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewCandidateWorks = `-- name: ListReviewCandidateWorks :many
SELECT
    w.href,
    w.name,
    w.image_url,
    w.release_date,
    w.category,
    w.created_at,
    w.updated_at
FROM works w
WHERE (?1 = '' OR w.category = ?1)
  AND (?2 = '' OR RTRIM(w.href, '/') = RTRIM(?2, '/'))
ORDER BY w.category ASC, w.href ASC
LIMIT CASE WHEN ?3 <= 0 THEN -1 ELSE ?3 END
`

type ListReviewCandidateWorksParams struct {
	Category  interface{}
	WorkHref  interface{}
	LimitRows interface{}
}

func (q *Queries) ListReviewCandidateWorks(ctx context.Context, arg ListReviewCandidateWorksParams) ([]Work, error) {
	rows, err := q.db.QueryContext(ctx, listReviewCandidateWorks, arg.Category, arg.WorkHref, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Work
	for rows.Next() {
		var i Work
		if err := rows.Scan(
			&i.Href,
			&i.Name,
			&i.ImageUrl,
			&i.ReleaseDate,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLatestReview = `-- name: UpsertLatestReview :exec
INSERT INTO latest_reviews (
    review_key,
    external_review_id,
    work_href,
    category,
    review_type,
    platform_key,
    review_url,
    review_date,
    score,
    quote,
    publication_name,
    publication_slug,
    author_name,
    author_slug,
    season_label,
    username,
    user_slug,
    thumbs_up,
    thumbs_down,
    version_label,
    spoiler_flag,
    source_payload_json,
    source_crawl_run_id,
    last_crawled_at,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19,
    ?20,
    ?21,
    ?22,
    ?23,
    ?24,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT(review_key) DO UPDATE SET
    external_review_id = excluded.external_review_id,
    work_href = excluded.work_href,
    category = excluded.category,
    review_type = excluded.review_type,
    platform_key = excluded.platform_key,
    review_url = excluded.review_url,
    review_date = excluded.review_date,
    score = excluded.score,
    quote = excluded.quote,
    publication_name = excluded.publication_name,
    publication_slug = excluded.publication_slug,
    author_name = excluded.author_name,
    author_slug = excluded.author_slug,
    season_label = excluded.season_label,
    username = excluded.username,
    user_slug = excluded.user_slug,
    thumbs_up = excluded.thumbs_up,
    thumbs_down = excluded.thumbs_down,
    version_label = excluded.version_label,
    spoiler_flag = excluded.spoiler_flag,
    source_payload_json = excluded.source_payload_json,
    source_crawl_run_id = excluded.source_crawl_run_id,
    last_crawled_at = excluded.last_crawled_at,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertLatestReviewParams struct {
	ReviewKey         string
	ExternalReviewID  sql.NullString
	WorkHref          string
	Category          string
	ReviewType        string
	PlatformKey       string
	ReviewUrl         sql.NullString
	ReviewDate        sql.NullString
	Score             sql.NullFloat64
	Quote             sql.NullString
	PublicationName   sql.NullString
	PublicationSlug   sql.NullString
	AuthorName        sql.NullString
	AuthorSlug        sql.NullString
	SeasonLabel       sql.NullString
	Username          sql.NullString
	UserSlug          sql.NullString
	ThumbsUp          sql.NullInt64
	ThumbsDown        sql.NullInt64
	VersionLabel      sql.NullString
	SpoilerFlag       sql.NullInt64
	SourcePayloadJson string
	SourceCrawlRunID  string
	LastCrawledAt     string
}

func (q *Queries) UpsertLatestReview(ctx context.Context, arg UpsertLatestReviewParams) error {
	_, err := q.db.ExecContext(ctx, upsertLatestReview,
		arg.ReviewKey,
		arg.ExternalReviewID,
		arg.WorkHref,
		arg.Category,
		arg.ReviewType,
		arg.PlatformKey,
		arg.ReviewUrl,
		arg.ReviewDate,
		arg.Score,
		arg.Quote,
		arg.PublicationName,
		arg.PublicationSlug,
		arg.AuthorName,
		arg.AuthorSlug,
		arg.SeasonLabel,
		arg.Username,
		arg.UserSlug,
		arg.ThumbsUp,
		arg.ThumbsDown,
		arg.VersionLabel,
		arg.SpoilerFlag,
		arg.SourcePayloadJson,
		arg.SourceCrawlRunID,
		arg.LastCrawledAt,
	)
	return err
}

const upsertReviewFetchStateFailed = `-- name: UpsertReviewFetchStateFailed :exec
INSERT INTO review_fetch_state (
    work_href,
    review_type,
    platform_key,
    status,
    last_attempted_at,
    last_fetched_at,
    last_run_id,
    last_error,
    last_error_type,
    last_error_stage,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    'failed',
    ?4,
    NULL,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
ON CONFLICT(work_href, review_type, platform_key) DO UPDATE SET
    status = 'failed',
    last_attempted_at = excluded.last_attempted_at,
    last_run_id = excluded.last_run_id,
    last_error = excluded.last_error,
    last_error_type = excluded.last_error_type,
    last_error_stage = excluded.last_error_stage,
    updated_at = excluded.updated_at
`

type UpsertReviewFetchStateFailedParams struct {
	WorkHref        string
	ReviewType      string
	PlatformKey     string
	LastAttemptedAt sql.NullString
	LastRunID       sql.NullString
	LastError       sql.NullString
	LastErrorType   sql.NullString
	LastErrorStage  sql.NullString
	UpdatedAt       string
}

func (q *Queries) UpsertReviewFetchStateFailed(ctx context.Context, arg UpsertReviewFetchStateFailedParams) error {
	_, err := q.db.ExecContext(ctx, upsertReviewFetchStateFailed,
		arg.WorkHref,
		arg.ReviewType,
		arg.PlatformKey,
		arg.LastAttemptedAt,
		arg.LastRunID,
		arg.LastError,
		arg.LastErrorType,
		arg.LastErrorStage,
		arg.UpdatedAt,
	)
	return err
}

const upsertReviewFetchStateRunning = `-- name: UpsertReviewFetchStateRunning :exec
INSERT INTO review_fetch_state (
    work_href,
    review_type,
    platform_key,
    status,
    last_attempted_at,
    last_fetched_at,
    last_run_id,
    last_error,
    last_error_type,
    last_error_stage,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    'running',
    ?4,
    NULL,
    ?5,
    NULL,
    NULL,
    NULL,
    ?6
)
ON CONFLICT(work_href, review_type, platform_key) DO UPDATE SET
    status = 'running',
    last_attempted_at = excluded.last_attempted_at,
    last_run_id = excluded.last_run_id,
    last_error = NULL,
    last_error_type = NULL,
    last_error_stage = NULL,
    updated_at = excluded.updated_at
`

type UpsertReviewFetchStateRunningParams struct {
	WorkHref        string
	ReviewType      string
	PlatformKey     string
	LastAttemptedAt sql.NullString
	LastRunID       sql.NullString
	UpdatedAt       string
}

func (q *Queries) UpsertReviewFetchStateRunning(ctx context.Context, arg UpsertReviewFetchStateRunningParams) error {
	_, err := q.db.ExecContext(ctx, upsertReviewFetchStateRunning,
		arg.WorkHref,
		arg.ReviewType,
		arg.PlatformKey,
		arg.LastAttemptedAt,
		arg.LastRunID,
		arg.UpdatedAt,
	)
	return err
}

const upsertReviewFetchStateSucceeded = `-- name: UpsertReviewFetchStateSucceeded :exec
INSERT INTO review_fetch_state (
    work_href,
    review_type,
    platform_key,
    status,
    last_attempted_at,
    last_fetched_at,
    last_run_id,
    last_error,
    last_error_type,
    last_error_stage,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    'succeeded',
    ?4,
    ?5,
    ?6,
    NULL,
    NULL,
    NULL,
    ?7
)
ON CONFLICT(work_href, review_type, platform_key) DO UPDATE SET
    status = 'succeeded',
    last_attempted_at = excluded.last_attempted_at,
    last_fetched_at = excluded.last_fetched_at,
    last_run_id = excluded.last_run_id,
    last_error = NULL,
    last_error_type = NULL,
    last_error_stage = NULL,
    updated_at = excluded.updated_at
`

type UpsertReviewFetchStateSucceededParams struct {
	WorkHref        string
	ReviewType      string
	PlatformKey     string
	LastAttemptedAt sql.NullString
	LastFetchedAt   sql.NullString
	LastRunID       sql.NullString
	UpdatedAt       string
}

func (q *Queries) UpsertReviewFetchStateSucceeded(ctx context.Context, arg UpsertReviewFetchStateSucceededParams) error {
	_, err := q.db.ExecContext(ctx, upsertReviewFetchStateSucceeded,
		arg.WorkHref,
		arg.ReviewType,
		arg.PlatformKey,
		arg.LastAttemptedAt,
		arg.LastFetchedAt,
		arg.LastRunID,
		arg.UpdatedAt,
	)
	return err
}
